



services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    env_file:
      - .env                     # This loads ALL variables
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env                     # Also loads POSTGRES_* for the database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: