# services:
#   nestjs_api_prod:
#     build:
#       context: .
#       dockerfile: Dockerfile.prod

#     ports:
#       - "3001:3001"
#     env_file:
#       - .env
#     depends_on:
#       - postgres

#     environment:
#       PORT: 3001
#       NODE_ENV: production
#       DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
#       RESEND_API_KEY: ${RESEND_API_KEY}
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}
#       REDIS_USERNAME: ${REDIS_USERNAME}
#       REDIS_PASSWORD: ${REDIS_PASSWORD}
#       JWT_SECRET: ${JWT_SECRET}
#       CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
#       CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
#       CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
#       FLW_SECRET_KEY: ${FLW_SECRET_KEY}
#       FLW_PUBLIC_KEY: ${FLW_PUBLIC_KEY}
#       FLW_SECRET_HASH: ${FLW_SECRET_HASH}
#       FRONTEND_URL: ${FRONTEND_URL}

  

#   postgres:
#     image: postgres:17

#     container_name: postgres
#     env_file:
#       - .env
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}

#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#     restart: unless-stopped

# volumes:
#   postgres_data:




services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    env_file:
      - .env                     # This loads ALL variables
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env                     # Also loads POSTGRES_* for the database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: