FROM node:24 AS builder

WORKDIR /app

COPY pnpm-lock.yaml package.json ./
# COPY ./src .

RUN corepack enable 


RUN pnpm install 

COPY . .

RUN pnpm prisma generate

RUN pnpm run build

RUN rm -rf ./src

EXPOSE 3000

CMD ["pnpm", "run", "start:prod"]


# production runtime  
FROM node:24 AS runner

WORKDIR /app 
ENV NODE_ENV=production 

COPY --from=builder /app/dist ./dist 
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["node", "dist/main.js"]